package Simulator.Clients;

class Passenger{
    enum STATE{
        AT_THE_DISEMBARKING_ZONE,
        AT_THE_LUGGAGE_COLLECTION_POINT,
        AT_THE_BAGGAGE_RECLAIM_OFFICE,
        EXITING_THE_ARRIVAL_TERMINAL,
        AT_THE_ARRIVAL_TRANSFER_TERMINAL,
        TERMINAL_TRANSFER,
        AT_THE_DEPARTURE_TRANSFER_TERMINAL,
        ENTERING_THE_DEPARTURE_TERMINAL
    }
    STATE curState;
    int TOTAL_NUMBER_OF_BAGS;
    int NUMBER_OF_BAGS_RETRIEVED;

    public Passenger(int numberOfBags)
    {
       curState = STATE.AT_THE_DISEMBARKING_ZONE;
       TOTAL_NUMBER_OF_BAGS = numberOfBags;
       NUMBER_OF_BAGS_RETRIEVED = 0;
    }
}